/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.sql.Connection;
import Base_Datos.Manejador_BD;
import com.mysql.jdbc.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import java.util.Random;
import java.util.Vector;
import java.util.*;
import javax.swing.*;



public class Diagnostico extends javax.swing.JFrame {
     Paciente paciente;
    Manejador_BD manejadorBD;
    String nombreMedico;
    int idMedico;
    public Diagnostico() {
        initComponents();
        manejadorBD =new Manejador_BD();
        paciente =new Paciente();
        
        cargarListaDoctores();
        
    }
    public void cargarListaDoctores(){
    
         try{
        manejadorBD.conectarseBD();
        
        ResultSet resultado= manejadorBD.consultarDB("select * from medico order by id_medico asc");
        
        //Vector model = new Vector();
       
        while(resultado.next()){
        //  model.addElement( new Item(resultado.getInt("id_medico"), resultado.getString("nombre_med")+ " " + resultado.getString("apellido_med") ) );
        comboDoctor.addItem(resultado.getString("nombre_med")+ " " + resultado.getString("apellido_med") );
        }
       
        //comboDoctor.setModel((ComboBoxModel<String>) model);
        //comboDoctor.setRenderer( new itemRender() );

        manejadorBD.cerrarConexionBD(); 
        }catch (Exception error){}
    }
    
    Connection con;
    PreparedStatement past;

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btnexportar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        tbnagregar = new javax.swing.JButton();
        comboDoctor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DIAGNOSTICO");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 340));

        jLabel1.setText("DESCRIPCION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 90, 30));

        jLabel2.setText("DOCTOR:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel3.setText("DIAGNOSTICO :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        txtDiagnostico.setColumns(20);
        txtDiagnostico.setRows(5);
        jScrollPane1.setViewportView(txtDiagnostico);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        btnexportar.setText("EXPORTAR  A  PDF");
        btnexportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexportarActionPerformed(evt);
            }
        });
        jPanel1.add(btnexportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        jLabel4.setText("FECHA :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 160, -1));

        tbnagregar.setText("agregar");
        tbnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnagregarActionPerformed(evt);
            }
        });
        jPanel1.add(tbnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        comboDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDoctorActionPerformed(evt);
            }
        });
        jPanel1.add(comboDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //String doctor=this.txtDoctor.getText();
       String diagnostico=this.txtDiagnostico.getText();
        Random rand = new Random();
         int maxNumber = 10000;
         int randomID = rand.nextInt(maxNumber) + 1;
    String fecha=this.txtFecha.getText();         
//Date fecha = new Date();
         /*String date = DateMatcher.group().trim();

        DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
Date myDate = formatter.parse(fecha);
java.sql.Date sqlDate = new java.sql.Date(myDate.getTime());*/



         System.out.println("nombre del paciente es : " +paciente.getNombre_paciente());
       try{
        manejadorBD.conectarseBD();
       manejadorBD.insertarDB("Insert into consulta(descripcion_consul,fecha_consul,id_medico,id_paciente) values('"+ diagnostico +"','"+ fecha +"',"+ idMedico+","+ paciente.getId_paciente() +")");
       
        manejadorBD.cerrarConexionBD();
         JOptionPane.showMessageDialog(null,"se resgistro correctamente");
       }
       catch(Exception error ){
           System.out.println("error de conexion : " +error.getMessage());
       }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnexportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexportarActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/progra","root","");
            JasperDesign jdesign= JRXmlLoader.load("C:\\Users\\H   P\\Documents\\NetBeansProjects\\Proyecto\\src\\reportes\\reporte.jasper");
            String query = "SELECT * FROM consulta and paciente and me";
                    /*"SELECT consulta.id_consulta,consulta.descripcion_consul,consulta.fecha_consul,medico.nombre_med, medico.apellido_med, paciente.nombre_paci, paciente.apellido_paci, paciente.edad_paci\n" +
        "FROM medico\n" +
        "INNER JOIN paciente\n" +
        "INNER JOIN consulta ON medico.id_medico = consulta.id_medico and paciente.id_paciente = consulta.id_paciente";*/
           
            JRDesignQuery updateQuery  =new JRDesignQuery(); 
             updateQuery.setText(query);
             
             jdesign.setQuery(updateQuery);
             
             JasperReport jreport = JasperCompileManager.compileReport(jdesign);
             JasperPrint jprint=JasperFillManager.fillReport(jreport,null,con);
             
             JasperViewer.viewReport(jprint);
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Diagnostico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Diagnostico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Diagnostico.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btnexportarActionPerformed

    private void tbnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnagregarActionPerformed
        // TODO add your handling code here:
        Doctor d=new Doctor();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
        
    }//GEN-LAST:event_tbnagregarActionPerformed

    private void comboDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDoctorActionPerformed
        // TODO add your handling code here:
        idMedico=comboDoctor.getSelectedIndex()+1;
        System.out.println("id del medico: " + idMedico);
        nombreMedico= comboDoctor.getSelectedItem().toString();
        System.out.println("nombre del medico: " + nombreMedico);

        
          
        
    }//GEN-LAST:event_comboDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnostico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexportar;
    private javax.swing.JComboBox<String> comboDoctor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tbnagregar;
    private javax.swing.JTextArea txtDiagnostico;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
